### PR TITLE
WiP: Iommu for Rust

### PR DESCRIPTION
**Pull request by huberste**
This branch / pull request makes ixy.rs use the intel(TM) IOMMU and thus makes ixy.rs safe(TM).
Right now it compiles and runs and does *not* make any computers explode (to my knowledge), which is good. The code might be ugly, though, and many unneeded comments and commented-out code fragments are still in there. Also, there are some error-checks missing, still.

### CODE REVIEW

**Comment by ackxolotl** [comment]
Nice pull request! :+1: Looking forward to the final version. Some things to be improved: `lib.rs`. I think actually all the changes in there are unnecessary. In `memory.rs`: `Dma<T>::allocate()` and `Mempool::allocate()` should borrow `dev` immutably instead of being passed a raw pointer if possible. For never used fields in the vfio structs consider using `#[allow(dead_code)]` or remove the fields in your final pull request. Oh, and you should run `cargo fmt` before your next commit, that would be great :)

**Review by ackxolotl — CHANGES_REQUESTED** [review]
Nice pull request! :+1: Looking forward to the final version. Some things to be improved: `lib.rs`. I think actually all the changes in there are unnecessary. In `memory.rs`: `Dma<T>::allocate()` and `Mempool::allocate()` should borrow `dev` immutably instead of being passed a raw pointer if possible. For never used fields in the vfio structs consider using `#[allow(dead_code)]` or remove the fields in your final pull request. Oh, and you should run `cargo fmt` before your next commit, that would be great :)

**Comment by huberste** [comment]
How about now?

**Comment by huberste** [comment]
How about now?

**Pull request closed without merging**
