### PR TITLE
CI Test

### PR DESCRIPTION
**Pull request by emmericp**
this should break the test in ixy-ci

### CODE REVIEW

**Comment by emmericp** [comment]
@ixy-ci ping

**Comment by emmericp** [comment]
@ixy-ci ping

**Comment by emmericp** [comment]
@ixy-ci test

**Comment by emmericp** [comment]
@ixy-ci ping

**Comment by emmericp** [comment]
@ixy-ci test

**Comment by emmericp** [comment]
@Bobo1239 why did this pass?

**Comment by Bobo1239** [comment]
If I'm not mistaken the touched byte is irrelevant for the test as it isn't part of the sequence number (last four bytes of the 60 byte packet). The pcap check only looks at the `ixy` at the start of the UDP payload and the sequence number at the end.

Changing to `p[56] = 1;` should fail the test I think.

**Comment by emmericp** [comment]
@ixy-ci ping

**Comment by emmericp** [comment]
i've added a commit but it apparently didn't trigger a test

**Comment by emmericp** [comment]
@ixy-ci test

**Comment by emmericp** [comment]
@ixy-ci test

**Comment by Bobo1239** [comment]
New pushes currently don't trigger test runs. Implementing that should be fairly simple (just emit a new job when the webhook message comes) but it's currently missing. (There are also some other UX improvements which I'd like to implement soon...)

**Comment by emmericp** [comment]
okay, cool, seems to be working in principle

**Comment by emmericp** [comment]
@ixy-ci ping

**Comment by emmericp** [comment]
@ixy-ci test

**Comment by emmericp** [comment]
@ixy-ci ping

**Comment by emmericp** [comment]
@ixy-ci test

**Comment by Bobo1239** [comment]
Hm, that shouldn't have happened... Currently working on making the captured `.pcap` downloadable so anyone can check. (It should already be present in the `logs` directory.)

**Comment by emmericp** [comment]
i think that was just a random cloud hiccup, not too unexpected that random failures sometimes happen when relying on a virtual network

(the sequence number duplicate is supposed to happen with this PR)

**Pull request closed without merging**
