### PR TITLE
Remove a redundant &Rc::clone

### PR DESCRIPTION
**Pull request by 197g**
An `Rc` instance is always necessary for packet construction, taking it
by value makes this clearer. It is then no longer necessary to put the
argument behin a reference in `alloc_pkt`. This avoid one call to 
`Rc::clone` in total and avoids a reference. Afaik llvm is not yet smart 
enough to fully convert this automatically during optimization passes 
beyond function boundaries. There's some weird interaction 
happening where then a compare and [some more instructions 
remain](https://play.rust-lang.org/?version=stable&mode=release&edition=2018&gist=e3f41f9be35b7493c182dfd58fa349e3). Actual performance results may or may not be unoticable in the end..

### CODE REVIEW

**Comment by ackxolotl** [comment]
Thanks for your pull request! I'll check this out later in the afternoon and do some performance measurements :)

**Comment by 197g** [comment]
I'd have another deeper PR that actually changes some interior mutability so that less `borrow_mut` checks have to be performed and to avoid an allocation when returning `Packet` from the queue during `clean_tx_queue`. It was built after this commit but does not strictly build on top of it. Should I push it here anyways or create another PR?

**Comment by ackxolotl** [comment]
Another PR would be great to see the impact of these changes on performance (independently of each other).

**Comment by 197g** [comment]
It should be possible to just cherry pick each commit individually if necessary. I'd really like to just submit these as `patch` files instead ^^ Edit: Oops, okay. I'll turn these into 3 independent PRs then if you want.

**Comment by 197g** [comment]
Okay, I removed the commits again, now the other PRs are #6 and #7 . Turns out the changes could be split into 3 separate changes.

**Comment by ackxolotl** [comment]
Haha, ok, no worries. I don't care that much about it ... could have cherry picked some commits as well but since you asked ... ;) Guess I'll merge all the commits anyway. Thanks for your contribution!

**Comment by 197g** [comment]
Are you going to post performance evaluation somewhere or should I drop by at the chair sometime if I'm curious?

**Comment by ackxolotl** [comment]
@HeroicKatora: We're going to update the performance measurements graphs in the ixy-languages repository soon ;) Spoiler: Your changes had an impact of about +0.5 mpps for each direction with bidirectional forwarding which is quite nice :-)

**Pull request merged**
